#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
cd "${SCRIPT_DIR}"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"

TASKS_OVERRIDE="${TASKS_OVERRIDE:-gsm8k:128}"
MODEL_DRAFT_PAIRS_OVERRIDE="${MODEL_DRAFT_PAIRS_OVERRIDE:-Qwen/Qwen3-4B|z-lab/Qwen3-4B-DFlash-b16}"
TEMPERATURES_OVERRIDE="${TEMPERATURES_OVERRIDE:-0.0}"
MODES_OVERRIDE="${MODES_OVERRIDE:-sdpa}"
TREE_BUDGET_OVERRIDE="${TREE_BUDGET_OVERRIDE:-128}"

RL_DIR="${RL_DIR:-runs/rl_tree}"
mkdir -p "${RL_DIR}"

# 1) Data collection with exploration.
TASKS_OVERRIDE="${TASKS_OVERRIDE}" \
MODEL_DRAFT_PAIRS_OVERRIDE="${MODEL_DRAFT_PAIRS_OVERRIDE}" \
TEMPERATURES_OVERRIDE="${TEMPERATURES_OVERRIDE}" \
MODES_OVERRIDE="${MODES_OVERRIDE}" \
TREE_BUDGET_OVERRIDE="${TREE_BUDGET_OVERRIDE}" \
DDTREE_ADAPTIVE_BRANCHING=0 \
DDTREE_COVERAGE_BRANCHING=0 \
DDTREE_BUDGET_PROPORTIONAL_BRANCHING=0 \
DDTREE_TARGET_LATENT_BRANCHING=0 \
DDTREE_PROB_THRESHOLD_BRANCHING=0 \
DDTREE_RL_BRANCHING=1 \
DDTREE_RL_EPSILON="${DDTREE_RL_EPSILON:-0.25}" \
DDTREE_RL_REWARD_LATENCY_PENALTY="${DDTREE_RL_REWARD_LATENCY_PENALTY:-0.05}" \
DDTREE_RL_LOG_PATH="${RL_DIR}/collect.jsonl" \
RUN_TAG="${RUN_TAG_COLLECT:-__rl_collect}" \
bash run_benchmark.sh

# 2) Train offline contextual-bandit policy.
python3 train_tree_rl_policy.py \
  --input-jsonl "${RL_DIR}/collect.jsonl" \
  --output-policy "${RL_DIR}/policy.json" \
  --ridge-lambda "${RIDGE_LAMBDA:-1.0}"

# 3) Evaluate learned policy (greedy action selection).
TASKS_OVERRIDE="${TASKS_OVERRIDE}" \
MODEL_DRAFT_PAIRS_OVERRIDE="${MODEL_DRAFT_PAIRS_OVERRIDE}" \
TEMPERATURES_OVERRIDE="${TEMPERATURES_OVERRIDE}" \
MODES_OVERRIDE="${MODES_OVERRIDE}" \
TREE_BUDGET_OVERRIDE="${TREE_BUDGET_OVERRIDE}" \
DDTREE_ADAPTIVE_BRANCHING=0 \
DDTREE_COVERAGE_BRANCHING=0 \
DDTREE_BUDGET_PROPORTIONAL_BRANCHING=0 \
DDTREE_TARGET_LATENT_BRANCHING=0 \
DDTREE_PROB_THRESHOLD_BRANCHING=0 \
DDTREE_RL_BRANCHING=1 \
DDTREE_RL_POLICY_PATH="${RL_DIR}/policy.json" \
DDTREE_RL_EPSILON=0.0 \
DDTREE_RL_REWARD_LATENCY_PENALTY="${DDTREE_RL_REWARD_LATENCY_PENALTY:-0.05}" \
DDTREE_RL_LOG_PATH="${RL_DIR}/eval.jsonl" \
RUN_TAG="${RUN_TAG_EVAL:-__rl_eval}" \
bash run_benchmark.sh

echo "RL pipeline complete."
echo "  Collection log: ${RL_DIR}/collect.jsonl"
echo "  Policy:         ${RL_DIR}/policy.json"
echo "  Eval log:       ${RL_DIR}/eval.jsonl"
